name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v4

    - name: Xcode Setup
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.1'

    - name: Build
      run: |
        cd WhatsAppClone1
        xcodebuild build -project WhatsAppClone1.xcodeproj -scheme WhatsAppClone1 clean build -sdk iphoneos CODE_SIGNING_ALLOWED=No

    - name: Run tests
      run: |
        cd WhatsAppClone1
        xcodebuild test -project WhatsAppClone1.xcodeproj -scheme WhatsAppClone1 clean build -sdk iphoneos -destination "platform=iOS Simulator,OS=16.1,name=iPhone 14 Pro Max" CODE_SIGNING_ALLOWED=No
