name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4

    - name: Set up Tuist
      run: |
        # Install Tuist using the official method
        curl -Ls https://install.tuist.io | bash
        echo "$HOME/.tuist" >> $GITHUB_PATH

    - name: Install dependencies with Tuist
      run: tuist fetch

    - name: Generate Xcode project with Tuist
      run: tuist generate

    - name: Xcode Setup
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0.1'

    - name: Build
      run: |
        xcodebuild build -workspace WhatsAppClone1.xcworkspace -scheme WhatsAppClone1 clean build -sdk iphoneos CODE_SIGNING_ALLOWED=No

    - name: Run tests
      run: |
        xcodebuild test -workspace WhatsAppClone1.xcworkspace -scheme WhatsAppClone1 clean build -sdk iphoneos -destination "platform=iOS Simulator,OS=17.0,name=iPhone 14 Pro Max" CODE_SIGNING_ALLOWED=No
